<?php

declare(strict_types=1);

namespace App\Module\Recipes\Domain\Repository;

use App\Module\Recipes\Domain\Entity\PlannedMeal;
use App\Module\Recipes\Domain\Enum\MealSlot;
use DateTimeImmutable;

/**
 * The meal plan's write-side port.
 *
 * There is deliberately no `findAll()` or date-range finder here: reading the
 * calendar is a query, and queries in this project go through DBAL (HMAI-390's
 * `GetMealPlan`), not through the repository. What the write side needs is the
 * ability to load one meal, store it, drop it, and answer the one question the
 * aggregate structurally cannot — whether this recipe is already planned for
 * this slot.
 *
 * The open point HMAI-389 handed over — what happens to a recipe that is
 * deleted while meals still point at it — is resolved in HMAI-390 as a block
 * (`existsForRecipe()` below, the Budget category precedent). The deciding
 * argument is the shopping list: it is generated by joining the plan to the
 * recipes, so a dangling reference would make it silently short by one meal's
 * worth of ingredients, and the user would find out at the shop rather than at
 * the moment of deletion. Cascading has the same defect from the other side —
 * it would edit a plan the user made, without being asked. The cost of the
 * block is that a recipe still sitting in an old plan entry cannot be deleted
 * until that entry is removed; since the plan is forward-looking and keeps no
 * archive, that is one action the user understands rather than a permanent
 * pin.
 */
interface MealPlanRepositoryInterface
{
    public function save(PlannedMeal $meal): void;

    public function findById(string $id): ?PlannedMeal;

    /**
     * Whether this recipe is already planned for this date and slot.
     *
     * `$excludingId` exists for the move: relocating a meal onto its own
     * current position must be a no-op success rather than a conflict with
     * itself — the same self-exclusion Budget's category rename needs.
     */
    public function existsFor(
        DateTimeImmutable $date,
        MealSlot $slot,
        string $recipeId,
        ?string $excludingId = null,
    ): bool;

    /**
     * Whether any meal at all is planned from this recipe.
     *
     * This is the delete guard, so it deliberately spans the whole calendar
     * rather than a window: a plan entry three weeks old references the recipe
     * just as much as tomorrow's does, and answering only for the visible
     * range would let a delete through that leaves a dangling row behind.
     */
    public function existsForRecipe(string $recipeId): bool;

    public function remove(PlannedMeal $meal): void;
}
