framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            series.ratings.cache:
                adapter: cache.adapter.redis
                default_lifetime: 3600
            cache.rate_limiter:
                adapter: cache.adapter.redis
                default_lifetime: 3600

when@test:
    framework:
        cache:
            pools:
                cache.rate_limiter:
                    adapter: cache.adapter.array
