framework:
    secret: '%env(APP_SECRET)%'

    session: true

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host']


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
