framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus: ~
            query.bus: ~
            event.bus: ~

        transports:
            in_memory:
                dsn: 'in-memory://'

        routing:
            App\Module\Series\Domain\Event\EpisodeRated: in_memory
